Specify nix cert
Matches what curl uses, presume that's fine. Not sure why this broke.
```
error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Problem with the SSL CA cert (path? access rights?) (77)
```