Adding push set upstream force
This is helpful when you get the following error message:
```
 ! [rejected]              rick/feat1 -> rick/feat1 (non-fast-forward)
error: failed to push some refs to 'github.com:some-org/some-rep.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
which can happen if you push to a branch that previously existed